### ISSUE TITLE
interpolate on own images

### ISSUE THREAD

**Issue by kootenpv** [facebookresearch/FaderNetworks#2]
Feature request: enable an `input_path` or `input_file` on which we can run the model to alter the input image. It would be best if an easy to run example would be provided :)

**Comment by chikiuso** [comment]
This project is quite similar to StarGAN (https://github.com/yunjey/StarGAN), I think it is not possible to use own image if you can't provide the 40 attributes (as listed on list_attr_celeba.txt) for your own image.

**Comment by glample** [comment]
You don't need to provide any attribute to use your own image. However, in our experiments the model did not work on our images, unless they have the same format as images in the dataset, i.e. they are cropped and centered exactly in the same way as celebA images. So we are not planning to release this feature. We could maybe do it if the script they use to center / crop their images was provided though.
