### ISSUE TITLE
does someone reproducing the results

### ISSUE THREAD

**Issue by Paseam** [facebookresearch/FaderNetworks#4]

**Comment by glample** [comment]
Are you able to reproduce the results using the pretrained models?

**Comment by jlezama** [comment]
Hi,
Are the default number of epochs and images per epoch the same as used in the paper?
 (1000/50000)
Thanks!

**Comment by glample** [comment]
Yes. Note that in practice we never run the model until the 1000th epoch. After 100 or 200 epochs the model has usually converged.

**Comment by shiv-gpt** [comment]
Hi,

I am running the model for image with sizes 64*64. Accordingly i have changed the number of layers to 4 instead of 6 as used for 256*256. Rest all is same. But i am not able to reproduce the results. Any suggestions on how i could change the model to make it work?

**Comment by glample** [comment]
Hi,
Is it not working at all? What do you observe? Did you look at the generations at different epochs during training?

**Comment by shiv-gpt** [comment]
I am attaching some of the results i am getting. I am just testing on the "EyeGlasses" attribute. 
On 256x256 with very little training i got this result: (I believe if i train for longer i will get better results but dont have the computational resources)
![eyeglasses](https://user-images.githubusercontent.com/35093471/39076558-0823fdc4-44ca-11e8-9049-5a729309e995.png)
On 64x64 after around 50 epochs i got this result:
![1](https://user-images.githubusercontent.com/35093471/39076634-72e6a4e0-44ca-11e8-9a4f-c74c41c95319.png)
On 64x64 after around 200 epochs i get this result:
![2](https://user-images.githubusercontent.com/35093471/39076665-b663f4d4-44ca-11e8-9f4e-4cb034ad939a.png)
I tried changing the model and was able to add a bit of the attribute but the reconstruction is a bit different from the original:
![7](https://user-images.githubusercontent.com/35093471/39076696-f26b4270-44ca-11e8-98e7-ab159d6a8638.png)

No, i haven't looked at the generations at different epochs yet. Please look into these results and suggest some solutions.

Thanks
Shivang

**Comment by glample** [comment]
Mmm 200 epochs is a bit low, but this should work at least a little bit. Also, I would try 5 layers for 64x64 images. Do you use skip-connections? If so, please try to remove them. Adding 1 or 2 skip-connections was okay for 6 or 7 layers, but more was detrimental. I never tried with 64x64 images, but with this resolution it might always be detrimental.

But more importantly, I think it's really important to look at different epochs. In our experiments, I was saving the model every 5 epochs and generating interpolations for each saved model, to see when the results are the best (the best epochs were very different across experiments).

Also, what values of `alpha` do you use to make the generations? Some attributes require larger values than others. The ones in the README should be fine though.
